export const SHOW_OVERLAY_ON_IMAGES = 'SHOW_OVERLAY_ON_IMAGES';
export const SET_IMAGES = 'SET_IMAGES';
export const SET_FILTERED_IMAGES = 'SET_FILTERED_IMAGES';
export const SET_FILTER = 'SET_FILTER';